add implement some functions such as getset strlen exist persist expire append in cli string(#188)
ByteStorage/FlyDB pull request #207
Opened 2023-07-13 10:22 UTC by wangchenguang123

![6fc07f9bcb2fe37bf63ade271a83fa0](https://github.com/ByteStorage/FlyDB/assets/56055887/3579bd4d-f23a-46f6-9041-d24968a3364a)
![6945427a16cdfce3af05359015c2919](https://github.com/ByteStorage/FlyDB/assets/56055887/8dccd54a-a1b2-4c34-b0db-338bcc430a09)

2023-07-13 10:28 UTC, sjcsjc123 commented
can show me when expire a key, can i get the key again?

2023-07-13 10:36 UTC, wangchenguang123 commented
> 

Oh, this is my mistake. When the key expires, I should further handle it. May I ask if it is a deletion or other operation

2023-07-13 10:36 UTC, wangchenguang123 commented
> can show me when expire a key, can i get the key again?

Oh, this is my mistake. When the key expires, I should further handle it. May I ask if it is a deletion or other operation

2023-07-13 12:36 UTC, sjcsjc123 commented
if expire, when get the key, it should create error to tell user the key is not existed

2023-07-13 12:40 UTC, wangchenguang123 commented
> if expire, when get the key, it should create error to tell user the key is not existed

ok，i know it

2023-07-14 02:09 UTC, qishenonly requested changes

2023-07-14 02:09 UTC, qishenonly commented on cmd/client/root.go
> +		Help: "get curvalue set newvalue",
The content of `Help` needs to be modified to indicate what data structure this is.  As shown in the figure below, you need to indicate which data structure to add or get data into.

The same below.

![image](https://github.com/ByteStorage/FlyDB/assets/90094807/4849a5c3-d89e-4c20-af48-1c0a2f1ceb0e)

2023-07-14 08:37 UTC, closed without merging